### ISSUE TITLE
Add Priorities to Commands

### ISSUE THREAD

**Issue by Koloss0** [UMSATS/tsat-utilities-kit#1]
The command configurations in `can_command_list.c` are all set to priority 0. This should be corrected to reflect the command reference doc

**Comment by whatdoes3plus1equalsto** [comment]
@Koloss0 For now, I only see the priority for common commands but not for the subsystem commands on TSAT-7 Command List document. Is there any other documents I should go over?

**Comment by Koloss0** [comment]
Hey @whatdoes3plus1equalsto. Thanks for looking into it. There's a list of subsystems at the bottom of the screen, it's easy to miss so I don't blame you. Also, I didn't officially assign this issue yet, but unfortunately I've already arranged with @SydSydPov that she would take on this issue as her first Software task.

I'm glad you're interested in working on TUK. Unfortunately, I'm a bit disorganized with tasks at the moment as I'm rethinking the design of how the CAN Wrapper will process messages. Currently, the only tasks I can give you are the ones labelled "good first task" or "research". Let me know which ones interest you and I can explain them more fully.
