### ISSUE TITLE
Update the CAN Command List

### ISSUE THREAD

**Issue by Koloss0** [UMSATS/tsat-utilities-kit#18]
Once again, the command list has been completely altered, [here](https://docs.google.com/spreadsheets/d/1fF_nCTbqJ7y3KoorSmB4DAGctDv61TSHfD0VK8CovCM/edit?gid=1728821240#gid=1728821240).

Every subsystem has been changed. You will need to update `can_command_list.h` to reflect the new list, as well as the body sizes and priorities in `can_command_list.c`. `SensorID` and `PowerLineID` can also be removed as they don't have a use anymore.

**Comment by ArnavG-it** [comment]
Some questions:
1. Do the ground station commands need to removed from `CmdID` or added to `cmd_configs`?
2. Should the size of `cmd_configs` be adjusted now that there are less commands?
3. `CMD_CDH_PROCESS_RETURN`'s argument size depends on the command ID. What should the body size be defined as?
4. Some payload commands use float arguments. Can we assume these are 4 bytes?

**Comment by Koloss0** [comment]
> Some questions:
> 1. Do the ground station commands need to removed from `CmdID` or added to `cmd_configs`?
> 2. Should the size of `cmd_configs` be adjusted now that there are less commands?
> 3. `CMD_CDH_PROCESS_RETURN`'s argument size depends on the command ID. What should the body size be defined as?
> 4. Some payload commands use float arguments. Can we assume these are 4 bytes?

1. Yeah, delete them. The Comms <-> Ground communication is still something I'm not entirely sure about. That's for another day.

2. Now that we decided not to assign the values, something you can do is add a final value called `NUM_COMMANDS` and use that for the array size.

3. Make it 7 bytes (that's the max it can be).

4. I think so. I'm going to run some tests on my STM32 nucleo board sometime today to make sure these assumptions are correct.
