### ISSUE TITLE
Investigate Safety of Tx Mailbox Loop

### ISSUE THREAD

**Issue by Koloss0** [UMSATS/tsat-utilities-kit#31]
Investigate whether this line of code is likely to get stuck in a loop:

```c
while (HAL_CAN_GetTxMailboxesFreeLevel(s_init_struct.hcan) == 0){}
```

This also violates one of NASA's big ten rules about putting safe guards on loops. So you should also put a sane limit on how many times this loop can repeat. To not interfere with normal functioning, you may want to learn a bit about the function before making an estimate on how many loops it might need to perform during normal operation.

**Comment by ArnavG-it** [comment]
If the loop isn't exiting, that would imply that all the mailboxes are full. We have timeout handling in `CANWrapper_Poll_Errors()` that calls the user's error callback, but as far as I can tell the timed out message still occupies the mailbox, and is still trying to be transmitted (unless automatic retransmission is disabled.) Also, apparently if a transmission fails enough times the CAN node will disconnect itself from the bus, so we should empty the mailboxes before that happens.

We could have the transmission aborted and mailbox emptied when a message times out using `HAL_CAN_AbortTxRequest()`. This could be done in the timeout handling process, although it would rely on the user polling for errors. As for the while loop, it shouldn't hang if the mailboxes are being managed, but we could still limit it and just return an error if it times out.

Let me know if that makes sense, or if you already implemented the mailbox management and I'm missing it.

**Comment by Koloss0** [comment]
> We have timeout handling in CANWrapper_Poll_Errors() that calls the user's error callback, but as far as I can tell the timed out message still occupies the mailbox, and is still trying to be transmitted (unless automatic retransmission is disabled.)

I think you might be mixing a couple things up a bit. `CANWrapper_Poll_Errors()` is a completely separate timeout detection mechanism laid on top of the lower-level mechanism that's part of the CAN protocol. We created it because CAN doesn't guarantee that the intended recipient acknowledged your message, only that *any* node in the network has acknowledged it.

In our supplementary mechanism, a message times out after a period elapses without receiving a matching acknowledgement message to the one that was previously transmitted. Messages that are being held for this purpose are stored in the `TxCache`, not the CAN mailboxes.

**Comment by Koloss0** [comment]
I looked at the source code for the `HAL_CAN_GetTxMailboxesFreeLevel` function (as it often comes to with HAL), and I made some interesting discoveries.

```c
/**
  * @brief  Return Tx Mailboxes free level: number of free Tx Mailboxes.
  * @param  hcan pointer to a CAN_HandleTypeDef structure that contains
  *         the configuration information for the specified CAN.
  * @retval Number of free Tx Mailboxes.
  */
uint32_t HAL_CAN_GetTxMailboxesFreeLevel(const CAN_HandleTypeDef *hcan)
{
  uint32_t freelevel = 0U;
  HAL_CAN_StateTypeDef state = hcan->State;

  if ((state == HAL_CAN_STATE_READY) ||
      (state == HAL_CAN_STATE_LISTENING))
  {
    /* Check Tx Mailbox 0 status */
    if ((hcan->Instance->TSR & CAN_TSR_TME0) != 0U)
    {
      freelevel++;
    }

    /* Check Tx Mailbox 1 status */
    if ((hcan->Instance->TSR & CAN_TSR_TME1) != 0U)
    {
      freelevel++;
    }

    /* Check Tx Mailbox 2 status */
    if ((hcan->Instance->TSR & CAN_TSR_TME2) != 0U)
    {
      freelevel++;
    }
  }

  /* Return Tx Mailboxes free level */
  return freelevel;
}
```

1. If the node state is in the sleep state or error state, this function returns `0`. If a node happens to enter that state, it would result in an infinite loop.
2. It's checking some registers to see if the mailboxes are full. I haven't found any code that resets the bits on these registers so I think it's being reset by the CAN controller itself after a message is sent.

**Comment by ArnavG-it** [comment]
Thanks for explaining what `CANWrapper_Poll_Errors()` is doing.

Am I right in thinking that we need to abort a transmission if it failed (outside of the timeout detection `Poll_Errors` is doing,) or does CAN handle this itself? 

> 2. It's checking some registers to see if the mailboxes are full. I haven't found any code that resets the bits on these registers so I think it's being reset by the CAN controller itself after a message is sent.

Interesting. Here's the code for the abort function I mentioned:
```c
/**
  * @brief  Abort transmission requests
  * @param  hcan pointer to an CAN_HandleTypeDef structure that contains
  *         the configuration information for the specified CAN.
  * @param  TxMailboxes List of the Tx Mailboxes to abort.
  *         This parameter can be any combination of @arg CAN_Tx_Mailboxes.
  * @retval HAL status
  */
HAL_StatusTypeDef HAL_CAN_AbortTxRequest(CAN_HandleTypeDef *hcan, uint32_t TxMailboxes)
{
  HAL_CAN_StateTypeDef state = hcan->State;

  /* Check function parameters */
  assert_param(IS_CAN_TX_MAILBOX_LIST(TxMailboxes));

  if ((state == HAL_CAN_STATE_READY) ||
      (state == HAL_CAN_STATE_LISTENING))
  {
    /* Check Tx Mailbox 0 */
    if ((TxMailboxes & CAN_TX_MAILBOX0) != 0U)
    {
      /* Add cancellation request for Tx Mailbox 0 */
      SET_BIT(hcan->Instance->TSR, CAN_TSR_ABRQ0);
    }

    /* Check Tx Mailbox 1 */
    if ((TxMailboxes & CAN_TX_MAILBOX1) != 0U)
    {
      /* Add cancellation request for Tx Mailbox 1 */
      SET_BIT(hcan->Instance->TSR, CAN_TSR_ABRQ1);
    }

    /* Check Tx Mailbox 2 */
    if ((TxMailboxes & CAN_TX_MAILBOX2) != 0U)
    {
      /* Add cancellation request for Tx Mailbox 2 */
      SET_BIT(hcan->Instance->TSR, CAN_TSR_ABRQ2);
    }

    /* Return function status */
    return HAL_OK;
  }
  else
  {
    /* Update error code */
    hcan->ErrorCode |= HAL_CAN_ERROR_NOT_INITIALIZED;

    return HAL_ERROR;
  }
}
```
It seems to be setting those registers you mentioned, which is why I ask if we might need to use this function for timeout handling.

**Comment by Koloss0** [comment]
> Note: I was writing this comment before you replied, so it doesn't address what you said.

So if the while loop is stuck in a loop, it could mean two things:

1. The node is in a sleep or error state.
2. The TX mailboxes are not emptying, likely because the CAN bus is busy with higher priority messages. How long it might be until there's an opening would be uncertain.

I'm not sure what a good limit would be for this loop. Here's some rough guessing I did:

The baud rate for the CAN bus is 500kbit/s and a CAN message is at maximum 112 bits. So that's ~4,464.29 messages per second. One message takes 0.224 milliseconds to send, so ten messages would take 2.24 milliseconds, which is approximately 179,200 instruction cycles (with an 80Mhz MCU). Assuming one iteration of the loop is about 24 instructions, it would take 7,466 iterations of the loop to reach this.

Btw just for fun I compiled the `HAL_CAN_GetTxMailboxesFreeLevel` into assembly code to get an idea of how many instructions there'd be in a single iteration. Here's the result of that:

```
HAL_CAN_GetTxMailboxesFreeLevel:
	ldrb	r3, [r0, #32]	@ zero_extendqisi2	@ hcan_13(D)->State, hcan_13(D)->State
	subs	r3, r3, #1	@ tmp128, hcan_13(D)->State,
	cmp	r3, #1	@ tmp128,
	bhi	.L100		@,
	ldr	r3, [r0]	@ _2, hcan_13(D)->Instance
	ldr	r0, [r3, #8]	@ _3, _2->TSR
	ldr	r2, [r3, #8]	@ _5, _2->TSR
	ldr	r3, [r3, #8]	@ _7, _2->TSR
	lsls	r2, r2, #4	@, _5,
	ubfx	r0, r0, #26, #1	@ <retval>, _3,
	it	mi
	addmi	r0, r0, #1	@ <retval>, <retval>,
	lsls	r3, r3, #3	@, _7,
	bpl	.L97		@,
	adds	r0, r0, #1	@ <retval>, <retval>,
	bx	lr	@
	movs	r0, #0	@ <retval>,
	bx	lr	@
```

It's 20 instructions. The actual loop + checking the condition was an additional 4 instructions.

**Comment by ArnavG-it** [comment]
> If the node state is in the sleep state or error state, this function returns 0. If a node happens to enter that state, it would result in an infinite loop.

Good catch. Could we add the same checks to `transmit_internal()` to avoid that case?

**Comment by Koloss0** [comment]
> 2.24 milliseconds

I just remembered that the timeout period for a CAN message is 3.6 milliseconds, which might be a bit close. I think we might be able to safely half that value and still be okay.

**Comment by Koloss0** [comment]
> Am I right in thinking that we need to abort a transmission if it failed (outside of the timeout detection Poll_Errors is doing,) or does CAN handle this itself? This is probably irrelevant to the issue but I figure it might be important.

I don't think we need to do anything. To my understanding, that function sets a bit which signals to the CAN controller to remove the message from the mailbox. That's kind of it. I don't think it's used for handling transmission failures.

**Comment by ArnavG-it** [comment]
> I don't think we need to do anything. To my understanding, that function sets a bit which signals to the CAN controller to remove the message from the mailbox. That's kind of it. I don't think it's used for handling transmission failures.

Oh okay, thanks for confirming. Limiting the loop should be all that's needed for case 2 then.

**Comment by Koloss0** [comment]
So, in summary:

- I think we should put a limit of 4,000 iterations on the loop. After which point an error is returned. (whether it should enqueue an  error to the error queue is another question)
- we should probably have a guard at the front of the function which checks if the node has entered one of the problematic states and returns pre-emptively if so, to prevent needless hogging of resources.

The problematic states are anything that isn't `HAL_CAN_STATE_READY` or `HAL_CAN_STATE_LISTENING`. See the enum definition below:

```c
typedef enum
{
  HAL_CAN_STATE_RESET             = 0x00U,  /*!< CAN not yet initialized or disabled */
  HAL_CAN_STATE_READY             = 0x01U,  /*!< CAN initialized and ready for use   */
  HAL_CAN_STATE_LISTENING         = 0x02U,  /*!< CAN receive process is ongoing      */
  HAL_CAN_STATE_SLEEP_PENDING     = 0x03U,  /*!< CAN sleep request is pending        */
  HAL_CAN_STATE_SLEEP_ACTIVE      = 0x04U,  /*!< CAN sleep mode is active            */
  HAL_CAN_STATE_ERROR             = 0x05U   /*!< CAN error state                     */

} HAL_CAN_StateTypeDef;
```

**Comment by ArnavG-it** [comment]
Here you are: 025e301

I'm not sure what errors to return so please fix those and let me know if anything else is wrong.

**Comment by Koloss0** [comment]
@ArnavG-it Four things:
- Return descriptive error codes to differentiate the failure cases from other types of errors. For example, `CAN_WRAPPER_TX_FAIL_BAD_CAN_STATE` and `CAN_WRAPPER_TX_MAILBOXES_FULL`.
- There is a subtle but critical bug in your code: `limiter` is 8 bits wide; meaning, it can only store values between 0-255. That means it will never be greater than `4000`, hence the limiter is defective. Using a fixed width type was a good choice though, as that is encouraged by MISRA C guidelines, so I would simply upgrade it to a `uint16_t` (which ranges 0-65,535).
- I'm going to be a bit pedantic here, but I would move the `++` operation to a separate line after the if statement. It's not wrong, but I think separating the comparison and increment operations helps improve readability. The most basic way to write something is often the clearest.
- You can add a comment giving a brief description of where the value `4000` comes from, and include a link to this discussion for more details.
